services:
  web:
    environment:
      - POSTGRES_SERVER=db
      - POSTGRES_PORT=5432
    volumes:
      - ./app:/web-backend/app
      - ./alembic:/web-backend/alembic
    command: uv run fastapi dev --host 0.0.0.0 --port 8000